### ISSUE TITLE
开发环境Mock.js找不到

### ISSUE THREAD

**Issue by 8-shen** [xxx-fe/mall-app#2]
http://localhost:3333/public/vendor/mockjs/dist/mock-min.js 404 not found，确定项目中有这个依赖？

**Comment by chenchangwen** [comment]
bower install.   
因为mockjs 在 bower 里面了 .

**Comment by chenchangwen** [comment]
> 感谢回复，现在好了
> 不过现在bower install之后，还是需要手工将mockjs目录复制到public/vendor，建议与bootstrap保持一致

好的, 谢谢 ,我会检查处理.
